{
 "title": "Jam Testnet",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Alice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Timeslot Alice",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_timeslot{instance=\"pyjamaz-alice:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tickets in accumulator",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tickets{instance=\"pyjamaz-alice:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total workreports accumulated",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_workreports_total{instance=\"pyjamaz-alice:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Bob", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Timeslot Bob",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_timeslot{instance=\"pyjamaz-bob:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tickets in accumulator",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tickets{instance=\"pyjamaz-bob:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total workreports accumulated",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_workreports_total{instance=\"pyjamaz-bob:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}