from pyjamaz.graypaper_constants import VALIDATOR_COUNT as GP_VALIDATOR_COUNT, EPOCH_TIMESLOTS as GP_EPOCH_TIMESLOTS

VALIDATORS_COUNT = 6  # GP_VALIDATOR_COUNT
EPOCH_LENGTH = 12  # GP_EPOCH_TIMESLOTS
TICKET_SUBMISSION_END_SLOT = 10  # GP_TICKET_SUBMISSION_END_SLOT


# VALIDATORS_COUNT = 1023  # GP_VALIDATOR_COUNT
# EPOCH_LENGTH = 600  # GP_EPOCH_TIMESLOTS
# TICKET_SUBMISSION_END_SLOT = 500  # GP_TICKET_SUBMISSION_END_SLOT
