#GP-0.7.1-section:I.4.4
PERIOD = 8 #A
MINIMUM_BALANCE_ITEM = 10 #BI
MINIMUM_BALANCE_OCTET = 1 #BL
MINIMUM_BALANCE_SERVICE = 100 #BS
CORE_COUNT = 341 #C
PREIMAGE_EXPUNGE_TIMESLOTS = 19200 #D
EPOCH_TIMESLOTS = 600 #E
AUDIT_BIAS_FACTOR = 2 #F
GAS_ACCUMULATION = 10_000_000 #GA
GAS_INVOKE = 50_000_000 #GI
GAS_REFINE = 5_000_000_000 #GR
GAS_TOTAL = 3_500_000_000 #GT
HISTORY = 8 #H
MAXIMUM_WORK_ITEMS = 16 #I
MAXIMUM_DEPENDENCIES_WORK_REPORT = 8 #J
MAXIMUM_EXTRINSIC_TICKETS = 16 #K
MAXIMUM_AGE_LOOKUP_ANCHOR = 14400 #L
TRANSFER_MEMO_SIZE = 128 #M
TICKET_ENTRIES = 2 #N
MAXIMIM_AUTHORIZATION_POOL_ITEMS = 8 #O
SLOT_PERIOD = 6 #P
MAXIMUM_AUTHORIZATION_QUEUE_ITEMS = 80 #Q
ROTATION_PERIOD_CORE = 10 #R
MINIMUM_PUBLIC_SERVICE_ID = 2**16 #S
MAXIMUM_NUMBER_EXTRINSICS_WORK_PACKAGE = 128 #T
UNAVAILABLE_WORK_REPLACEMENT_PERIOD = 5 #U
VALIDATOR_COUNT = 1023 #V
MAXIMUM_SIZE_IS_AUTH_CODE = 64_000 #WA
MAXIMUM_SIZE_WORK_PACKAGE = 13_791_360 #WB
MAXIMUM_SIZE_SERVICE_CODE = 4_000_000 #WC
SIZE_ERASURE_CODED_PIECES = 684 #WE
MAXIMUM_NUMBER_IMPORTS_WORK_PACKAGE = 3072 #WM
MAXIMUM_SIZE_ENCODED_WORK_PACKAGE = 6 #WP
EC_SEGMENT_SIZE = MAXIMUM_SIZE_ENCODED_WORK_PACKAGE * SIZE_ERASURE_CODED_PIECES # WG
MAXIMUM_SIZE_ENCODED_WORK_REPORT = 48*2**10 #WR
SIZE_TRANSFER_MEMO = 128 #WT
MAXIMUM_NUMBER_EXPORTS_WORK_PACKAGE = 3072 #WX
#XX		X
TICKET_SUBMISSION_END_SLOT = 500 #Y
PVM_DYNAMIC_ALIGNMENT_FACTOR = 2 #ZA
PVM_INPUT_DATA_SIZE = 2**24 #ZI
PVM_PAGE_SIZE = 2**12 #ZP
PVM_SEGMENT_SIZE = 2**16 #ZQ
PVM_INIT_ZONE_SIZE = 2**16 #ZZ

COMMON_ERA = 1735732800

from pyjamaz.settings import TEST_SUITE
if TEST_SUITE == 'tiny':
    EPOCH_TIMESLOTS = 12 #E
    TICKET_SUBMISSION_END_SLOT = 10 #Y
    VALIDATOR_COUNT = 6 #V
    CORE_COUNT = 2 #C
    TICKET_ENTRIES = 3 #N
    MAXIMUM_EXTRINSIC_TICKETS = 3  # K
    ROTATION_PERIOD_CORE = 4  # R
    PREIMAGE_EXPUNGE_TIMESLOTS = 32 #D=
    MAXIMUM_AUTHORIZATION_QUEUE_ITEMS = 80  # Q
    MAXIMIM_AUTHORIZATION_POOL_ITEMS = 8  # O
    EC_SEGMENT_SIZE = 4104 #WG
    MAXIMUM_SIZE_ENCODED_WORK_PACKAGE = 1026 #WP TODO should be swapped with WE?
    SIZE_ERASURE_CODED_PIECES = 4 # WE TODO should be swapped with WP?
    GAS_TOTAL = 20_000_000  # GT
    GAS_REFINE = 1_000_000_000  # GR
    MAXIMUM_AGE_LOOKUP_ANCHOR = 24 # L
