#GP-0.3.8-section:I.4.4
PERIOD = 8 #A
MINIMUM_BALANCE_ITEM = 10 #BI
MINIMUM_BALANCE_OCTET = 1 #BL
MINIMUM_BALANCE_SERVICE = 100 #BS
CORE_COUNT = 341 #C
PREIMAGE_EXPUNGE_TIMESLOTS = 28800 #D
EPOCH_TIMESLOTS = 600 #E
AUDIT_BIAS_FACTOR = 2 #F
GAS_ACCUMULATION = 10000000 #GA
GAS_INVOKE = 50000000 #GI
GAS_REFINE = 5000000000 #GR
GAS_TOTAL = 3500000000 #GT
HISTORY = 8 #H
MAXIMUM_WORK_ITEMS = 4 #I
MAXIMUM_DEPENDENCIES_WORK_REPORT = 8 #J
MAXIMUM_EXTRINSIC_TICKETS = 16 #K
MAXIMUM_AGE_LOOKUP_ANCHOR = 14400 #L
TRANSFER_MEMO_SIZE = 128 #M
TICKET_ENTRIES = 2 #N
MAXIMIM_AUTHORIZATION_POOL_ITEMS = 8 #O
SLOT_PERIOD = 6 #P
MAXIMUM_AUTHORIZATION_QUEUE_ITEMS = 80 #Q
ROTATION_PERIOD_CORE = 10 #R
MAXIMUM_ENTRIES_ACCUMULATION_QUEUE = 1024 #S
UNAVAILABLE_WORK_REPLACEMENT_PERIOD = 5 #U
VALIDATOR_COUNT = 1023 #V
SIZE_ERASURE_CODED_PIECES = 648 #WC
MAXIMUM_ENTRIES_WORK_PACKAGE_MANIFEST = 2^11 #WM
MAXIMUM_SIZE_ENCODED_WORK_PACKAGE = 6 #WP
MAXIMUM_SIZE_ENCODED_WORK_REPORT = 48*2**10 #WR
SIZE_TRANSFER_MEMO = 128 #WT
#XX		X
TICKET_SUBMISSION_END_SLOT = 500 #Y
PVM_DYNAMIC_ALIGNMENT_FACTOR = 2 #ZA
PVM_INPUT_DATA_SIZE = 2**24 #ZI
PVM_PAGE_SIZE = 2**12 #ZP
PVM_SEGMENT_SIZE = 2**16 #ZQ
PVM_INIT_ZONE_SIZE = 2**16 #ZZ

COMMON_ERA = 1704110400  #T

from pyjamaz.settings import TEST_SUITE
if TEST_SUITE == 'tiny':
    EPOCH_TIMESLOTS = 12 #E
    TICKET_SUBMISSION_END_SLOT = 10 #Y
    VALIDATOR_COUNT = 6 #V
    CORE_COUNT = 2 #C
    TICKET_ENTRIES = 3 #N
    MAXIMUM_EXTRINSIC_TICKETS = 3  # K
    ROTATION_PERIOD_CORE = 4  # R

