from scalecodec.types import Struct, Tuple, Vec, Option, U8, U32, H256, I64, Bool


class WorkReport(Struct):
    #GP-equation: 130 | "WORK_REPORT"->"(AUTHORIZERS_HASH,OUTPUT,REFINEMENT_CONTEXT,WORK_PACKAGE,RESULTS)" | "AUTHORIZERS_HASH"->"32BYTEHASH" | "OUTPUT"->"BLOB" | "REFINEMENT_CONTEXT"->"(ANCHOR_HEADER_HASH,ANCHOR_POSTERIOR_STATE_ROOT,POSTERIOR_BEEFY_ROOT,LOOKUP_ANCHOR_HEADER_HASH,LOOKUP_ANCHOR_TIMESLOT,OPTION<WORK_PACKAGE_HASH>)" | "ANCHOR_HEADER_HASH"->"32BYTEHASH" | "ANCHOR_POSTERIOR_STATE_ROOT"->"32BYTEHASH" | "POSTERIOR_BEEFY_ROOT"->"32BYTEHASH" | "LOOKUP_ANCHOR_HEADER_HASH"->"32BYTEHASH" | "LOOKUP_ANCHOR_TIMESLOT"->"U32" | "WORK_PACKAGE_HASH"->"32BYTEHASH" | "WORK_PACKAGE"->"(WORK_PACKAGE_HASH,WORK_PACKAGE_LENGTH,ERASURE_ROOT,SEGMENT_ROOT)" | "WORK_PACKAGE_HASH"->"32BYTEHASH" | "WORK_PACKAGE_LENGTH"->"U32" | "ERASURE_ROOT"->"32BYTEHASH" | "SEGMENT_ROOT"->"32BYTEHASH" | "RESULTS"->"VEC<RESULT>" | "RESULT"->"(SERVICE_IDX,CODE_HASH,PAYLOAD_HASH,GAS_PRIORIZATION_RATIO,ERROR)" | "SERVICE_IDX"->"U32" | "CODE_HASH"->"32BYTEHASH" | "PAYLOAD_HASH"->"32BYTEHASH" | "GAS_PRIORIZATION_RATIO"->"S64" | "ERROR"->"ENUM<OUT-OF-GAS,UNEXPECTED-TERMINATION,BAD,BIG>"
    arguments = {
        'authorizers_hash': H256,
        'output': Vec(U8),
        'refinement_context': Tuple(H256,H256,H256,H256,U32,Option(H256)),
        'work_package': Tuple(H256,U32,H256,H256),
        #TODO Implement ENUM 'results': Vec(Tuple(U32,H256,H256,I64,"TODO:ENUM"))
        'results': Vec(Tuple(U32, H256, H256, I64, Bool))
    }
